<a href="https://colab.research.google.com/github/ummataliyev/DataScience/blob/main/1_creating_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
data1 = [3.5, 5, 6, 2] # list
arr1 = np.array(data1) # array1

In [3]:
data1

[3.5, 5, 6, 2]

In [5]:
arr1

array([3.5, 5. , 6. , 2. ])

In [8]:
data2 = (4, 5, 3.2, 7) # tuple
arr2 = np.array(data2)

In [9]:
arr2

array([4. , 5. , 3.2, 7. ])

In [10]:
arr1.ndim # size of array1

1

In [11]:
arr2.ndim # size of array2

1

In [18]:
# two-dimensional arrays
data3 = [[1, 2, 3, 4 ], [5, 6, 7, 8]] # nested list (a list within a list)
arr3 = np.array(data3) # array3

In [13]:
data3

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [19]:
arr3


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
arr3.shape # to see the number of rows and columns

(2, 4)

In [22]:
arr3.size # to see number of elments

8

In [23]:
arr4 =  np.zeros(shape=(2, 4)) # creating an array of size (2, 4) with all elements equal to 0
arr4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
arr5 = np.ones((2, 4)) # craeting an array of size (2, 4) with all elements equal to 1
arr5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
arr6 = np.arange(4, 20, 2) # places values ​​from 4 to 20 into an array in 2 increments
arr6

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
arr7 = np.arange(20) # places values fronm 0 to 20 into an arrat in 1 increments
arr7

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])